name: Ubuntu CI

on: 
  push:
    branches: [ master ]
  pull_request:
    braincehs: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.cfg.os }}
    name: ${{ matrix.cfg.os }}@latexmk

    strategy:
      matrix:
        cfg:
          - {os: ubuntu-latest'}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install latexmk
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y latexmk texlive texlive-full inkscape wget curl sed grep
    - name: Build with Make
      run: |
        make
