name: Ubuntu CI

on: 
  push:
    branches: [ master ]
  pull_request:
    braincehs: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.cfg.os }}
    name: ${{ matrix.cfg.os }}@latexmk

    strategy:
      matrix:
        cfg:
          - {os: ubuntu-latest, python-version: 3.9}

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install latexmk
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y latexmk texlive texlive-full inkscape wget curl sed grep

    - name: Install Python requirements
      shell: bash
      run: |
        python -m pip install -r requirements.txt
    - name: Build with Make
      run: |
        make all
